################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
ASM_UPPER_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
Book3rdEdition/C8X_Control \
Book3rdEdition/C8X_Control/DSP8_CCS4/TalkThru_6713 \
Book3rdEdition/C8X_Control/DSP8_CCS4/TalkThru_6713/Release \
Book3rdEdition/C8X_Control/DSP8_CCS4/TalkThru_OMAP \
Book3rdEdition/C8X_Control/DSP8_CCS4/TalkThru_OMAP/Release \
Book3rdEdition/C8X_Control/Win32/Release \
Book3rdEdition/C8X_Control/x64/Release \
Book3rdEdition/C8X_DAQ \
Book3rdEdition/C8X_DEBUG/DSP8_CCS5/TalkThru_6713 \
Book3rdEdition/C8X_DEBUG/DSP8_CCS5/TalkThru_6713/Debug \
Book3rdEdition/C8X_DEBUG/DSP8_CCS5/TalkThru_LCDK/Debug \
Book3rdEdition/C8X_DEBUG/DSP8_CCS5/TalkThru_LCDK \
Book3rdEdition/C8X_DEBUG/DSP8_CCS5/TalkThru_OMAP/Debug \
Book3rdEdition/C8X_DEBUG/DSP8_CCS5/TalkThru_OMAP \
Book3rdEdition/C8X_DEBUG \
Book3rdEdition/Reflashing\ LCDK\ for\ winDSK8 \
Book3rdEdition/code/appendix_a \
Book3rdEdition/code/appendix_f/ccs/codegen/lib/funFilter/examples \
Book3rdEdition/code/appendix_f/ccs/codegen/lib/funFilter \
Book3rdEdition/code/appendix_f/ccs/codegen/lib/funFilter/interface \
Book3rdEdition/code/appendix_f/ccs/codegen/mex/funFilter \
Book3rdEdition/code/appendix_f/ccs/codegen/mex/funFilter/interface \
Book3rdEdition/code/chapter_02/ccs/MyTalkThrough \
Book3rdEdition/code/chapter_03/ccs/FIRrevA \
Book3rdEdition/code/chapter_03/ccs/FIRrevB \
Book3rdEdition/code/chapter_03/ccs/FIRrevC \
Book3rdEdition/code/chapter_03/ccs/FIRrevD \
Book3rdEdition/code/chapter_04/ccs/IIRrevA \
Book3rdEdition/code/chapter_05/ccs/PN \
Book3rdEdition/code/chapter_05/ccs/resonator \
Book3rdEdition/code/chapter_05/ccs/sigGen \
Book3rdEdition/code/chapter_05/ccs/sigGenTable \
Book3rdEdition/code/chapter_06/ccs/Frame \
Book3rdEdition/code/chapter_06/ccs/Frame_EDMA_6713 \
Book3rdEdition/code/chapter_06/ccs/Frame_EDMA_6748 \
Book3rdEdition/code/chapter_07/ccs/FiltFrm \
Book3rdEdition/code/chapter_07/ccs/FiltFrm_6748 \
Book3rdEdition/code/chapter_08/c/fft_example \
Book3rdEdition/code/chapter_09/ccs/FFT_EDMA \
Book3rdEdition/code/chapter_09/ccs/FFT_FRAME \
Book3rdEdition/code/chapter_10/ccs/Echo \
Book3rdEdition/code/chapter_11/ccs/GraphEq \
Book3rdEdition/code/chapter_12/ccs \
Book3rdEdition/code/chapter_13/ccs/PPM \
Book3rdEdition/code/chapter_14/ccs \
Book3rdEdition/code/chapter_15/ccs/AMtx \
Book3rdEdition/code/chapter_16/ccs/AMrx \
Book3rdEdition/code/chapter_17/ccs/PLL \
Book3rdEdition/code/chapter_18/ccs/DigTx \
Book3rdEdition/code/chapter_18/ccs/DigTxIM \
Book3rdEdition/code/chapter_19/ccs/DigRx \
Book3rdEdition/code/chapter_20/ccs/QPSK_Tx \
Book3rdEdition/code/chapter_21/ccs/QPSK_AGC \
Book3rdEdition/code/chapter_21/ccs/QPSK_Rx \
Book3rdEdition/code/common_code/6713 \
Book3rdEdition/code/common_code/LCDK \
Book3rdEdition/code/common_code/Zoom \
Book3rdEdition/winDSK8 \

