/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 24-Sep-2019 13:25:49
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II Transposed
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
  5.123205967418e-06,2.049282386967e-05,3.073923580451e-05,2.049282386967e-05,
  5.123205967418e-06
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.743506761739,    5.262903798233,   -3.292943284665,
      0.773628219466
};
