/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 17-Sep-2019 13:25:56
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\extern\include\tmwtypes.h 
 */
const int BL = 31;
const real64_T B[31] = {
   0.006602857640047,   0.0164284900051,-0.008757708130169,  -0.0135491970697,
   0.002561467319379,  0.02216986523099, 0.003990335954309, -0.03005783217097,
   -0.01727085893138,  0.03782658344278,  0.04116157339534, -0.04428815719416,
   -0.09157382713625,  0.04857506132113,   0.3132861598887,   0.4499224644976,
     0.3132861598887,  0.04857506132113, -0.09157382713625, -0.04428815719416,
    0.04116157339534,  0.03782658344278, -0.01727085893138, -0.03005783217097,
   0.003990335954309,  0.02216986523099, 0.002561467319379,  -0.0135491970697,
  -0.008757708130169,   0.0164284900051, 0.006602857640047
};
